### ISSUE TITLE
Map 

### ISSUE THREAD

**Issue by gregdaynes** [Canary-PrintDesign/canswe#13]
I would love this to be interactive, with hover states on each of the location bullets, lets go for simple mvp first.

Will need to track down an svg map of Canada

Keep in mind this is in multiple places around the site, but with slightly different layouts.

**Comment by LouisRitchie** [comment]
PR for better css https://github.com/Canary-PrintDesign/canswe/pull/46

This would be improved further if the generated map could be made larger.
