### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by gregdaynes** [Canary-PrintDesign/canswe#17]
will need the Canary contact form added

**Comment by adamish717** [comment]
I'll add the contact form soon and you guys can style around it

**Comment by adamish717** [comment]
@LouisRitchie I would just copy the KMA layout and style, minus the map (as they don't have retail sales). Instead of a map, we can import Greg's map or just have a big-ass link to the Retailers page.

**Comment by adamish717** [comment]
https://www.kmacpa.ca/contact/
