### ISSUE TITLE
Homepage "Products by Canse"

### ISSUE THREAD

**Issue by adamish717** [Canary-PrintDesign/canswe#37]
Greg 'thinks' he did this, but I don't think it's done. The heading and stuff is up, but padding and images are not.

I'd like to make a major change from the design proof on this area.

Design shows boxes, but if we follow those links through to their conclusion, it basically just links to the "all our products" page, which seems silly.

Lets keep the top area the same, and instead of product groups, lets have Poly Pro 3600 and the Nylon Poly Pro and have them ribbon'd with a "Top Seller" across a top corner or something.

There's probably a better idea out there, but that's where I'm at right now

**Comment by gregdaynes** [comment]
Oh home page. No I didn't touch home page. Sorry for the confusion
