### ISSUE TITLE
Product tweaks

### ISSUE THREAD

**Issue by adamish717** [Canary-PrintDesign/canswe#40]
Needs to be updated as per the attached image

**Comment by adamish717** [comment]
![product-tweaks](https://user-images.githubusercontent.com/3332843/40191916-a8c4f4d4-59b7-11e8-8bf6-229fb540ea6a.jpg)

**Comment by adamish717** [comment]
@LouisRitchie I'd really love this polished up. This is something the client noticed and asked for, so I don't want to show him anything until it's done.

**Comment by gregdaynes** [comment]
- [x] Aligned Icons
- [x] out-of indication
- [x] Missing Fields
- [x] Safety Icon
