### ISSUE TITLE
Add generic privacy policy page

### ISSUE THREAD

**Issue by adamish717** [Canary-PrintDesign/canswe#84]
That link should probably link to something...

**Comment by LouisRitchie** [comment]
When I was at Reelgood, we used this: https://www.iubenda.com/en/

**Comment by LouisRitchie** [comment]
If we want to host this on our own site, i.e. have our own privacy policy page, then I can get to work on designing it. However, Iubenda gives a pretty easy way of making a privacy policy that is hosted by them, which we can link to. That basically means that @adamish717 would have to go figure out Iubenda and generate a policy. I'm happy to do this work if you like but I think it's out of my wheelhouse.

**Comment by adamish717** [comment]
I made a terrible page. It works and I shall never look back.
