### ISSUE TITLE
Estimate for "proximity" on location search map page

### ISSUE THREAD

**Issue by adamish717** [Canary-PrintDesign/canswe#93]
How many hours to have a GPS location pull and show local things? Probably too much.

SUPER rough estimate. Like, read this and then write a number.

**Comment by gregdaynes** [comment]
Yeah, no. Doable, but not within reason.

**Comment by gregdaynes** [comment]
![image](https://user-images.githubusercontent.com/43543/42545186-4b3aa924-846b-11e8-87b1-8da969fb89ed.png)

**Comment by adamish717** [comment]
Thanks, I'll let him know.
