### ISSUE TITLE
Sub-Categories!!

### ISSUE THREAD

**Issue by adamish717** [Canary-PrintDesign/canswe#96]
Client wants sub-categories within safety-pants.

Each product has been updated with a new piece of data called "sub-category" and is either 3600, 4100, or chaps.

The Products Page will now show "Safety Pants" and within that:

3600 Series
Meets WCB PPE 1 – 1997 Regulation

4100 Series
Exceeds WCB PPE 1 – 1997 Regulation

Chaps
Meets WCB PPE 1 – 1997 Regulation

**Comment by gregdaynes** [comment]
This is going to require a bunch of more thinking.

**Comment by gregdaynes** [comment]
Fixed with #111
